language: python

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=docs
  - TOXENV=pypy
  - TOXENV=cov

install:
  - git config --global user.email "travisci@jasonantman.com"
  - git config --global user.name "travisci"
  - pip install tox
  - pip install codecov
  - pip freeze

script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  except:
    - /^noci-.*$/
